/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jdict;

import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Blue
 */
public class FavoriteDictUI extends javax.swing.JDialog {
    FavoriteDict favDict;

    /**
     * Creates new form FavoriteDictUI
     */
    public FavoriteDictUI() {        
        initComponents();
        favDict = FavoriteDict.getInstance();       
        loadWordList();
    }
    
    private void loadWordList() {
        for(int i = 0; i < favDict.getSize(); i++) {
            Record record = favDict.getItem(i);
            cboWord.addItem(record.getWord());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboWord = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnViewMeaning = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMeaning = new javax.swing.JTextArea();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Từ");

        btnViewMeaning.setText("Xem nghĩa");
        btnViewMeaning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMeaningActionPerformed(evt);
            }
        });

        txtMeaning.setEditable(false);
        txtMeaning.setColumns(20);
        txtMeaning.setRows(5);
        jScrollPane2.setViewportView(txtMeaning);

        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cboWord, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnViewMeaning)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewMeaning)
                    .addComponent(btnDelete))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewMeaningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMeaningActionPerformed
        int wordIndex = cboWord.getSelectedIndex();
        Record record = favDict.getItem(wordIndex);
        txtMeaning.setText(record.getMeaning());
    }//GEN-LAST:event_btnViewMeaningActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int index = cboWord.getSelectedIndex();
        if(index != -1) {
            DefaultComboBoxModel model = (DefaultComboBoxModel) cboWord.getModel();
            model.removeElementAt(index);
            favDict.remove(index);
            favDict.save();            
        }
    }//GEN-LAST:event_btnDeleteActionPerformed
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnViewMeaning;
    private javax.swing.JComboBox<String> cboWord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtMeaning;
    // End of variables declaration//GEN-END:variables
}
