/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jdict;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;

/**
 *
 * @author Blue
 */
public class JDictUI extends javax.swing.JFrame {
    Dict dict;
    FavoriteDict favDict;
    ArrayList<Statistics> wordStatistics;
    
    public JDictUI() {
        initComponents();
        dict = AnhVietDict.getInstance();
        favDict = FavoriteDict.getInstance();
        loadStatistics();        
    }
    
    private void createStatistics() {
        wordStatistics = new ArrayList();
        try {
            FileOutputStream file = 
                    new FileOutputStream(Global.STATISTICS_FILE_PATH);
            file.close();
        } catch (Exception ex) {}
    }
    
    private void loadStatistics() {
        try {
            FileInputStream fileIn = 
                    new FileInputStream(Global.STATISTICS_FILE_PATH);
            ObjectInputStream input = new ObjectInputStream(fileIn);
            wordStatistics = (ArrayList<Statistics>) input.readObject();
            input.close();
            fileIn.close();
        } catch (Exception ex) {
            System.out.println(ex);
            createStatistics();
        }
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gpDict = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMeaning = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtWord = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        rbtnAV = new javax.swing.JRadioButton();
        rbtnVA = new javax.swing.JRadioButton();
        btnAddToFavorite = new javax.swing.JButton();
        btnStatistics = new javax.swing.JButton();
        btnShowFavorite = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JDict");
        setMinimumSize(new java.awt.Dimension(370, 310));

        txtMeaning.setEditable(false);
        txtMeaning.setColumns(20);
        txtMeaning.setRows(5);
        jScrollPane1.setViewportView(txtMeaning);

        jLabel1.setText("Từ điển");

        jLabel2.setText("Từ cần tra");

        txtWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWordActionPerformed(evt);
            }
        });
        txtWord.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtWordKeyReleased(evt);
            }
        });

        btnSearch.setText("Tra cứu");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        gpDict.add(rbtnAV);
        rbtnAV.setSelected(true);
        rbtnAV.setText("Anh - Việt");
        rbtnAV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnAVActionPerformed(evt);
            }
        });

        gpDict.add(rbtnVA);
        rbtnVA.setText("Việt - Anh");
        rbtnVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnVAActionPerformed(evt);
            }
        });

        btnAddToFavorite.setText("Lưu");
        btnAddToFavorite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToFavoriteActionPerformed(evt);
            }
        });

        btnStatistics.setText("Thống kê");
        btnStatistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatisticsActionPerformed(evt);
            }
        });

        btnShowFavorite.setText("Xem các từ đã lưu");
        btnShowFavorite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowFavoriteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtWord, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbtnAV)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtnVA)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAddToFavorite)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnShowFavorite)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnStatistics)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rbtnAV)
                    .addComponent(rbtnVA))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddToFavorite)
                    .addComponent(btnStatistics)
                    .addComponent(btnSearch)
                    .addComponent(btnShowFavorite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnAVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnAVActionPerformed
        dict = AnhVietDict.getInstance();
    }//GEN-LAST:event_rbtnAVActionPerformed

    private void rbtnVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnVAActionPerformed
        dict = VietAnhDict.getInstance();
    }//GEN-LAST:event_rbtnVAActionPerformed
        
    private void statistics(String word) {            
        wordStatistics.add(new Statistics(word));
        saveStatistics();
    }
    
    private void saveStatistics() {
        try (FileOutputStream fileOut = new FileOutputStream(Global.STATISTICS_FILE_PATH)) {
            ObjectOutputStream output = new ObjectOutputStream(fileOut);
            output.writeObject(wordStatistics);
            output.close();
        } catch (Exception ex) {
            System.out.println(ex);
        }        
    }
    
    private void search() {
        String word = txtWord.getText();
        
        int indexOfWord;
        
        if((indexOfWord = dict.findWord(word)) >= 0) {
            Record record = dict.getItem(indexOfWord);
            txtMeaning.setText(record.getMeaning());
            
            statistics(word);
        }
    }
    
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        search();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnStatisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatisticsActionPerformed
        StatisticsUI statistics = new StatisticsUI();
        statistics.setModal(true);
        statistics.show();
    }//GEN-LAST:event_btnStatisticsActionPerformed

    private void btnAddToFavoriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToFavoriteActionPerformed
        String word = txtWord.getText();
        if(dict.findWord(word) >= 0 && favDict.findWord(word) < 0) {
            int wordIndex = dict.findWord(word);
            Record record = dict.getItem(wordIndex);
            favDict.add(record);
            favDict.save();
        }
    }//GEN-LAST:event_btnAddToFavoriteActionPerformed

    private void btnShowFavoriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowFavoriteActionPerformed
        FavoriteDictUI favUI = new FavoriteDictUI();
        favUI.setModal(true);        
        favUI.show();
    }//GEN-LAST:event_btnShowFavoriteActionPerformed

    private void txtWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWordActionPerformed
         search();
    }//GEN-LAST:event_txtWordActionPerformed

    private final ActionListener searchWord = new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent e) {
        String word = ((JMenuItem) e.getSource()).getText();
        txtWord.setText(word);
        search();
      }
    };        
    
    private void txtWordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWordKeyReleased
        String word = txtWord.getText();
        JPopupMenu popup = new JPopupMenu();    
        ArrayList<String> similarWords = dict.findSimilars(word);
        for(int i = 0; i < similarWords.size(); i++) {
            JMenuItem item = new JMenuItem(similarWords.get(i));
            item.addActionListener(searchWord);
            popup.add(item);            
        }                    
        
        popup.show(txtWord, txtWord.getX(), txtWord.getY());
        
        txtWord.requestFocus();
    }//GEN-LAST:event_txtWordKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDictUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDictUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDictUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDictUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JDictUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToFavorite;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnShowFavorite;
    private javax.swing.JButton btnStatistics;
    private javax.swing.ButtonGroup gpDict;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtnAV;
    private javax.swing.JRadioButton rbtnVA;
    private javax.swing.JTextArea txtMeaning;
    private javax.swing.JTextField txtWord;
    // End of variables declaration//GEN-END:variables
}
