package jdict;

import java.io.FileInputStream;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;

public class StatisticsUI extends javax.swing.JDialog {       
    ArrayList<Statistics> wordStatistics;
    public StatisticsUI() {        
        initComponents();
        loadStatistics();
        loadTableData();
    }
    
    private int statisticsInWeek(String word) {
        int count = 0;
        
        for(int i = 0; i < wordStatistics.size(); i++) {
            Statistics statistics = wordStatistics.get(i);
            if(statistics.getWord().equals(word) && statistics.isThisWeek())
                count++;
        }
        
        return count;
    }
    
    private int statisticsInMonth(String word) {
        int count = 0;
        
        for(int i = 0; i < wordStatistics.size(); i++) {
            Statistics statistics = wordStatistics.get(i);
            if(statistics.getWord().equals(word) && statistics.isThisMonth())
                count++;
        }
        
        return count;
    }
    
    private ArrayList<String> findAllWords() {
        ArrayList<String> words = new ArrayList();
        for(int i = 0; i < wordStatistics.size(); i++) {
            Statistics statistics = wordStatistics.get(i);
            String word = statistics.getWord();
            if(words.indexOf(word) < 0) 
                words.add(word);
        }      
        return words;
    }
    
    private void loadTableData() {
        DefaultTableModel model = (DefaultTableModel) tbStatistics.getModel();   
        ArrayList<String> words = findAllWords();
        for(int i = 0; i < words.size(); i++) {
            Object[] data = new Object[3];
            String word = words.get(i);
            data[0] = word;
            data[1] = statisticsInWeek(word);
            data[2] = statisticsInMonth(word);
            
            model.addRow(data);
        }        
    }
    
    private void loadStatistics() {
        try {
            FileInputStream fileIn =
                    new FileInputStream(Global.STATISTICS_FILE_PATH);
            ObjectInputStream input = new ObjectInputStream(fileIn);
            wordStatistics = (ArrayList<Statistics>) input.readObject();
            input.close();
            fileIn.close();
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbStatistics = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbStatistics.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Từ", "Tuần", "Tháng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbStatistics);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbStatistics;
    // End of variables declaration//GEN-END:variables
}
